controller_server:
  ros__parameters:
    map_frame: world  # Global frame for the map
    odom_frame: world  # Local odometry frame
    base_frame: wamv/base_link  # Robot base frame
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      max_linear_accel: 0.3
      lookahead_dist: 2.0
      min_lookahead_dist: 0.5
      rotate_to_heading_angular_vel: 0.5
      use_velocity_scaled_lookahead_dist: true
      max_angular_vel: 0.5

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugin_names: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

behavior_server:
  ros__parameters:
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "/home/alexis/ros2_ws/src/depot.yaml"  # Correct path to map file

waypoint_follower:
  ros__parameters:
    use_sim_time: true

global_costmap:
  ros__parameters:
    global_frame: world
    robot_base_frame: wamv/base_link
    width: 500         # Largeur de la carte de coût (en nombre de cellules)
    height: 500        # Hauteur de la carte de coût (en nombre de cellules)
    resolution: 1.0   # Résolution de la carte de coût (en mètres par cellule)
    robot_radius: 0.5 # Rayon du robot (en mètres)


local_costmap:
  ros__parameters:
    global_frame: world
    robot_base_frame: wamv/base_link
    width: 100         # Largeur de la carte locale (en nombre de cellules)
    height: 100        # Hauteur de la carte locale (en nombre de cellules)
    robot_radius: 0.5 # Rayon du robot (en mètres)
    resolution: 1.0   # Résolution de la carte locale (en mètres par cellule)





    