controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5  # Adjust for boat speed
      max_linear_accel: 0.3
      lookahead_dist: 2.0
      min_lookahead_dist: 0.5
      rotate_to_heading_angular_vel: 0.5
      use_velocity_scaled_lookahead_dist: true
      max_angular_vel: 0.5
      critics:  # List of critics for path evaluation
        - RotateToGoal
        - Oscillation
        - ObstacleFootprint
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist

      critic_configs:
        ObstacleFootprint:
          scale: 1.0
        PathAlign:
          scale: 32.0
        GoalAlign:
          scale: 24.0
        PathDist:
          scale: 32.0
        GoalDist:
          scale: 24.0
        RotateToGoal:
          scale: 32.0
        Oscillation:
          scale: 1.0

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugin_names: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

behavior_server:
  ros__parameters:
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "map.yaml"

waypoint_follower:
  ros__parameters:
    use_sim_time: true
